version: '3.4'

services:
  visualizationserver:
    image: visualizationserver
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - ./db.sqlite3:/app/db.sqlite3
    ports:
      - 8000:8000
